---
galaxy_info:
  role_name: webserver
  author: lab
  description: Nginx web server role
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
dependencies:
  - role: common
